spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://pios-server.database.windows.net:1433;database=pios-test;currentSchema=pios;
    username: pios-admin
    password: Ukrajina44
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true
  mvc:
    log-request-details: true
hr.tvz.pios:
  secret: pios-secret